- Project.toml
- src/AccretionFormulae/orbit-interpolations.jl
- src/Gradus.jl
- src/GradusBase/GradusBase.jl
- src/GradusBase/geometry.jl
- src/Rendering/Rendering.jl
- src/Rendering/point-functions.jl
Previously had the interpolation type hard coded, but now we will infer it on the fly to be more robust to upstream changes.
> Deduce interpolation type in plunging velocities

- docs/src/overview/examples.md
- src/Gradus.jl
- src/GradusBase/GradusBase.jl
- src/GradusBase/geodesic-solutions.jl
- src/GradusBase/physical-quantities.jl
- src/orbits/emission-radii.jl
- src/special-radii.jl
Also corrected a function `event_horizon` to `eventhorizon` so that it actually gets exported, and added a new keyword for calculating impact parameters for a given radius, such that the maximum integration time may be set.
> New example: concentric rings

- Project.toml
- src/GradusBase/GradusBase.jl
- src/GradusBase/geometry.jl
- src/accretion-geometry/discs.jl
- src/accretion-geometry/meshes.jl
- src/corona-to-disc/transfer-functions.jl
- src/metrics/boyer-lindquist-ad.jl
- src/metrics/dilaton-axion-ad.jl
- src/metrics/johannsen-ad.jl
- src/metrics/johannsen-psaltis-ad.jl
- src/metrics/kerr-refractive-ad.jl
- src/metrics/morris-thorne-ad.jl
- src/orbits/circular-orbits.jl
- src/orbits/emission-radii.jl
- src/redshift.jl
- src/tracing/method-implementations/auto-diff.jl
- src/tracing/tracing.jl
- test/Project.toml
- test/unit/gradusbase.geometry.jl
Fixed the Gram-Schmidt implementation, which now correctly gives tetrad basis that reduces to Minkowski, so we can use it to map angles from local to global frame.
Also addresses #50 with a small fix.
Various other minor API changes and fixes, and more unit tests.
> Tetrad basis and various fixes

- Project.toml
- src/Gradus.jl
- src/GradusBase/GradusBase.jl
- src/GradusBase/geometry.jl
- src/corona-to-disc/corona-models.jl
- src/corona-to-disc/disc-profiles.jl
- src/corona-to-disc/flux-calculations.jl
- src/corona-to-disc/transfer-functions.jl
- src/metrics/dilaton-axion-ad.jl
- src/orbits/circular-orbits.jl
- src/orbits/orbit-interpolations.jl
- src/redshift.jl
- src/tracing/method-implementations/auto-diff.jl
- src/tracing/tracing.jl
- test/runtests.jl
- test/unit/gradusbase.geometry.jl
Implemented a model for calculating source to disc (reflected) flux for stationary lamp-posts that is metric generic, based off of the tetrad formalism from the previous commits.
It's worth noting that there are analytic LNR frames and bases that can be written in terms of the metric and inverse metric components analytically for stationary, axis-symmetric spacetimes, which will probably outperform the Gram-Schmidt algorithm I've written. These should seriously be added should this line become performance critical! I've left them out for now because I quite like the Gram-Schmidt process, and invested time getting it to work 👍 
Once the isotropic angle mapping for other metrics is done (PR soon hopefully), then the 2d-transfer function calculations should be ready to work with any of our …
> Generic source-to-disc flux

- Project.toml
- src/GradusBase/geometry.jl
- src/corona-to-disc/corona-models.jl
- src/corona-to-disc/flux-calculations.jl
- src/corona-to-disc/sky-geometry.jl
- test/smoke-tests/disc-profiles.jl
I _think_ this is now an okay way to map local sky angles to coordinate 4-velocity vectors for all supported metrics (bar #52). The reflected flux calculated in the reverberation lags is a little higher than previously, but given that these are abstract units we can rescale as (/if) needed
Here standard is the old sampler, which was lifted from a Younsi et al. (2016) paper (I think) and wasn't every really checked.
The photon paths disagree a little between the two methods:
But agree completely for the flat case (M = eps).
The full reverberation transfer functions calculated differ insignificantly.
Hopefully the doc-string for the method is detailed enough to illustrate how this was done. Generated documentation updates to follow!
> Metric generic angle mapping

- .github/workflows/docs.yml
- docs/Project.toml
- docs/src/index.md
Trying to get Buckets.jl to resolve via git in the documentation build.
> Documentation build fixes

- Project.toml
- src/transfer-functions/cunningham-transfer-functions.jl
- src/transfer-functions/integration.jl
- src/transfer-functions/precision-solvers.jl
- test/smoke-tests/cunningham-transfer-functions.jl
- test/smoke-tests/line-profiles.jl
Transfer functions were being incorrectly calculated for large impact parameters -- presumably due to something in the way these are mapped in curve space. Everything seems to be fixed by just scaling the observer position with target emission radius, so that is done here.
Updated test values to reflect improved precision, and now use mean instead of sum as the validation metric, since number of points may change.
Also changed the root finder algorithm to Root's Order0, since this dramatically improves performance.
> Transfer functions: change root finding algorithm and scale initial position

- Project.toml
- src/corona-to-disc/corona-models.jl
- src/corona-to-disc/sky-geometry.jl
Allows the experienced user to call into `Gradus.sky_angles_to_velocity`.
> Chore: move angle mapping function

- Project.toml
- src/Gradus.jl
- src/tracing/constraints.jl
- src/tracing/method-implementations/auto-diff.jl
- src/tracing/tracing.jl
- src/tracing/utility.jl
- test/smoke-tests/tracegeodesics.jl
Discontinue all support for regular (heap allocated) arrays as `u` and `v`, as this not only makes the integration system convoluted, but is also entirely unused and a complete performance degredation even on GPUs (#8).
This PR also brings #8 a step closer to being supported in main despite the poorer performance vs. multithreading.
> Feat: SVector as common currency

- Project.toml
- src/Gradus.jl
- src/GradusBase/geodesic-solutions.jl
- src/accretion-geometry/bootstrap.jl
- src/image-planes/planes.jl
- src/line-profiles.jl
- src/tracing/constraints.jl
- src/tracing/method-implementations/first-order.jl
- src/tracing/tracing.jl
- src/tracing/utility.jl
- src/transfer-functions/precision-solvers.jl
- src/transfer-functions/transfer-functions-2d.jl
- src/utils.jl
```julia
using Gradus
m = KerrMetric(M = 1.0, a = 1.0)
u = @SVector [0.0, 1e6, deg2rad(60), 0.0]
d = GeometricThinDisc(Gradus.isco(m), 500.0, deg2rad(90.0))
model = LampPostModel()
plane = PolarPlane(GeometricGrid(); Nr = 800, Nθ = 800)
begin
GC.gc()
tf = @time lagtransfer(model, m, u, plane, d, callback = domain_upper_hemisphere())
end
```
This might start getting quite confusing, but there is now a new ensemble method in Gradus which reuses integrators _provided only the endpoints of the geodesic_ are needed -- `EnsembleEndpointThreads`. This saves a considerable number of allocations, as can be seen above.
The same principle could also be used anywhere where the full solutions aren't required, such as in the precision integrators -- instead of setting up a full solution again, we just …
> Feat: better put out the bins for garbage collection

- Project.toml
- benchmark/integrator/benchmark-tracing.jl
- benchmark/runbenchmarks.jl
- src/Gradus.jl
- src/GradusBase/GradusBase.jl
- src/GradusBase/geodesic-solutions.jl
- src/GradusBase/metric-params.jl
- src/rendering/rendering.jl
- src/rendering/utility.jl
- src/tracing/callbacks.jl
- src/tracing/method-implementations/first-order.jl
- src/tracing/tracing.jl
Tried very hard to get the first order methods to work with the new `EnsembleEndpointThreaded`, but alas, there is some state being shared in the problem parameters within a thread that ruins subsequent solves and i have no idea what is causing it. The only way to fix it is to reinstantiate the integrator after each solve, which just defeats the point of it.
So I've added instead a warning that the endpoint threading method does not work, and then let it automatically change to `EnsembleThreaded`. Made all tests pass.
Also closes #87 -- the progress bar was causing all of the problems, so that can now be optionally passed to `tracegeodesics`, and incremented thread-safe and contextually. This does mean it's now much easier to add new progress meters to other methods too that don't rely on …
> Feat: render unto first-order

- Project.toml
- src/Gradus.jl
- src/line-profiles.jl
- src/orbits/orbit-interpolations.jl
- src/special-radii.jl
- src/tracing/callbacks.jl
- src/tracing/charts.jl
- src/tracing/method-implementations/first-order.jl
- src/tracing/tracing.jl
- src/transfer-functions/cunningham-transfer-functions.jl
- src/transfer-functions/integration.jl
- src/transfer-functions/transfer-functions-2d.jl
- test/integration/test-charts.jl
- test/runtests.jl
Adds `AbstractChart` as a method for changing the integration domain flexibly. Also adds a chart that uses `event_horizon` to interpolate the shape of the inner horizon poloidally, allowing better visualisations of shadows for non spherical event horizons.
```julia
using Gradus
using Plots
m = JohannsenPsaltisMetric(1.0, 0.8831, 0.4)
u = SVector(0.0, 1000.0, π / 2, 0.0)
α, β, img = @time rendergeodesics(
m,
u,
2000.0,
image_width = 1000,
image_height = 1000,
fov = 60.0 ,
verbose = true,
chart = event_horizon_chart(m, closest_approach = 1.001, resolution=200),
)
```
> Feat: charts

- Project.toml
- src/Gradus.jl
- src/corona-to-disc/corona-models.jl
- src/corona-to-disc/disc-profiles.jl
- src/transfer-functions/cunningham-transfer-functions.jl
- src/transfer-functions/transfer-functions-2d.jl
- src/transfer-functions/types.jl
There's a mistake in the emissivity profile as it is currently being calculated; it should be
$$
\varepsilon(r) = \frac{N(r)}{g^2 A(r, \text{d}r)},
$$
but we currently are missing the divide by redshift, where here the redshift if for the disc element and X-ray source respectively
$$
g^{-1} = \frac{E_\text{disc}}{E_\text{source}}.
$$
This is a little annoying to implement as currently the lag transfer functions don't track the model, but they probably should.
> Feat: disc emissivity

- Project.toml
- src/Gradus.jl
- src/accretion-geometry/bootstrap.jl
- src/accretion-geometry/geometry.jl
- src/tracing/callbacks.jl
- src/tracing/precision-solvers.jl
- test/integration/test-precision.jl
- test/runtests.jl
Hitting an apple on the corona at $1000\ r_\text{g}$ with a single geodesic, loading another for Gessler incase we miss.
Using Nelder-Mead to find $(\alpha, \beta)$ that strikes any arbitrary point in space, with or without disc geometry to ridiculous (and desired) precision!
> Feat: Wilhelm Tell

- Project.toml
- src/Gradus.jl
- src/metrics/kerr-newman-ad.jl
- src/special-radii.jl
- src/tracing/geodesic-problem.jl
- src/tracing/method-implementations/auto-diff.jl
- src/tracing/method-implementations/first-order.jl
- src/tracing/tracing.jl
- src/tracing/utility.jl
- test/runtests.jl
- test/smoke-tests/rendergeodesics.jl
- test/smoke-tests/tracegeodesics.jl
- test/unit/metrics.kerr-newman.jl
The event horizon is not being correctly calculated for this metric yet, suggesting there is a typo somewhere but I can't seem to find it.
There's also the ambiguity between the EH being
$$
\left. \frac{1}{g_{rr}}\right \rvert_{r_\text{EH}} = 0,
$$
or the Killing horizon corresponding to the $\frac{\partial}{\partial t}$ and $\frac{\partial}{\partial \phi}$ Killing vectors, i.e.
$$
\left. \left( g_{t\phi}^2 - g_{tt} g_{\phi \phi} \right) \right\rvert_{r_\text{EH}} = 0.
$$
They should be the same. For the Kerr-Newman metric currently implemented, they are not when $|a|>0$.. so... that needs to be fixed.
Also missing tests.
> Feat: Kerr-Newman metric

- Project.toml
- src/GradusBase/geometry.jl
- src/corona/emissivity.jl
- src/corona/sky-geometry.jl
- src/metrics/boyer-lindquist-ad.jl
- src/tracing/utility.jl
- test/Project.toml
- test/runtests.jl
- test/unit/coronal-beaming.jl
- test/unit/gradusbase.geometry.jl
Once the tests are all passing, this will be good to merge.
A tetrad is effectively a way of defining a locally flat coordinate system. The tetrad allows one to construct a series of orthonormal local basis vectors
$$
\frac{\partial}{\partial x^\mu} = e_\mu^{(i)},
$$
and a corresponding frame
$$
dx^\mu = e^\mu_{(i)},
$$
that translate vectors from global to local coordinates, and vice versa. Note that the index of the "local" picture is here in parenthesis and using latin characters -- this is just a convention to differentiate which is the local and which the global coordinate. $\mu$ expresses Boyer-Lindquist components $t, r, \theta, \phi$, whereas $i$ is a simple counter $0, 1, 2, 3$, for which we make an association to the BL components to motivate an interpretation (e.g. $0$ always …
> fix: relativistic beaming

- Project.toml
- docs/code/examples.jl
- docs/code/getting-started.jl
- docs/src/examples.md
- docs/src/getting-started.md
- ext/GradusDiffEqGPUExt/GradusDiffEqGPUExt.jl
- src/Gradus.jl
- src/const-point-functions.jl
- src/point-functions.jl
- src/rendering/rendering.jl
- src/rendering/utility.jl
- src/special-radii.jl
- src/tracing/charts.jl
- src/tracing/configuration.jl
- src/tracing/geodesic-problem.jl
- src/tracing/method-implementations/auto-diff.jl
- src/tracing/tracing.jl
- src/utils.jl
Closes #8 
There's still a lot of work to do here:
This PR currently includes a temporary fix for handling sin / cos duals in ForwardDiff when dispatching on Metal.
Rudimentary benchmarks look very promising (fully Float32):
```julia
sols = @btime tracegeodesics(m, us, vs, 2000.0f0)
sols = @btime tracegeodesics(m, us, vs, 2000.0f0,
solver = GPUTsit5(), ensemble = EnsembleGPUKernel(Metal.MetalBackend())
)
```
However, the traces themselves do not. On the CPU, we get:
Whereas on the GPU:
Clearly there is something very wrong here. Since the impact parameters are set for $\alpha$ between 5 and 10, the lack of spread in the GPU picture might suggest that the initial steps of the integrator are poor, which then propagates further into the integration. 
The performance is promising, and …
> Add GPU support

- src/Gradus.jl
- src/geometry/discs.jl
- src/plotting-recipes.jl
- src/redshift.jl
- src/tracing/precision-solvers.jl
- src/transfer-functions/cunningham-transfer-functions.jl
- src/transfer-functions/utils.jl
- test/runtests.jl
- test/transfer-functions/test-thick-disc.jl
Transfer functions can now be obscured on the disc:
> Feat: transfer functions for thick discs

- src/transfer-functions/cunningham-transfer-functions.jl
- src/transfer-functions/integration.jl
Attempt to fix different problems with the transfer functions.
The seam in this figure corresponds to the bin edge $g^\ast \in [0, h]$ and $g^\ast \in [1-h, 1]$. I tried a few different schemes to resolve this, but I think it's a combination of getting the timing wrong, and also the flux in the bin edges being too low with that Dauser approximation?
> Transfer function API and integration fixes

- src/corona/samplers.jl
- src/geometry/discs.jl
- src/geometry/discs/thick-disc.jl
- src/plotting-recipes.jl
- src/solution-processing.jl
- src/tracing/precision-solvers.jl
- src/transfer-functions/cunningham-transfer-functions.jl
- test/transfer-functions/test-thick-disc.jl
Basically, the conclusion of investigating #160 is that the root finder thinks it can see emission radii that are actually obscured. It's amazing just how big of an impact this really has, but tweaking the old visibility tolerance parameter helped the two curves line up in places. So it's clear we need a better visibility criteria: the question is just what?
I tried to make the `_is_visible` function more robust in this PR. Instead of just checking the proximity of a trajectory, traced with the full thick disc, to the target emission radius (which is biased towards concluding visible at small radii), the first simple change is to check the Cartesian distance between the target point and the geodesic endpoint.
This isn't however always enough, and requires recomputing the geodesic too …
> Fix: try to improve the visibility criteria

- src/tracing/configuration.jl
- src/transfer-functions/cunningham-transfer-functions.jl
- src/transfer-functions/utils.jl
It seems that for thick discs a ridiculously high tolerance is needed to correctly evaluate the Jacobian. Added logic that changes the jacobian tolerances within some unstable radius to ensure the transfer functions are still well behaved.
> fix: jacobian calculations with thick discs

- src/tracing/precision-solvers.jl
- src/transfer-functions/cunningham-transfer-functions.jl
- src/transfer-functions/integration.jl
- test/transfer-functions/test-thick-disc.jl
I actually had a really cool idea for this one:
$$
\left\lvert \frac{\partial r }{ \partial r_\text{e}} \right\rvert = \lvert \sin\theta \rvert^{-1}, 
$$
and then
$$
\left\lvert \frac{\partial(\alpha, \ \beta)}{\partial(r_\text{e}, \ g^\ast)} 
\right\rvert = 
\left\lvert 
\frac{\partial(\alpha, \ \beta)}{\partial(r, \ g^\ast)}
\right\rvert \left\lvert \frac{\partial r }{ \partial r_\text{e}} \right\rvert.
$$
Cool huh? Especially since in general $\delta r > \delta r_\text{e}$.
Well, $\lvert \partial h  / \partial r_\text{e} \rvert$ can be evaluated with AD from the cross section function, and then we can do 
$$
\left\lvert \frac{\partial(\alpha, \ \beta)}{\partial(r_\text{e}, \ g^\ast)} 
\right\rvert = 
\left\lvert 
\frac{\partial(\alpha, \ \beta)}{\partial(h, \ g^\ast)}
\right\rvert …
> Another attempt at some transfer function fixes

- src/corona/profiles/analytic.jl
- src/corona/profiles/radial.jl
- src/orbits/orbit-solving.jl
- src/transfer-functions/transfer-functions-2d.jl
- src/transfer-functions/types.jl
- src/utils.jl
- test/transfer-functions/test-2d.jl
This pull request adds extrapolation to the orbit-solving interpolation. The `extrapolate=true` argument has been added to the `LinearInterpolation` function calls in the `PlungingInterpolation` struct.
> Add extrapolation to orbit-solving interpolation

- lib/GradusSpectralModels/src/GradusSpectralModels.jl
- src/corona/profiles/radial.jl
- src/interpolations.jl
- src/reverberation.jl
- src/tracing/precision-solvers.jl
- src/transfer-functions/cunningham-transfer-functions.jl
- src/transfer-functions/integration.jl
- src/utils.jl
- test/transfer-functions/test-thick-disc.jl
- test/unit/interpolations.jl
Closes #202 and does a little bit towards #198, noting that the old Roots solver is a little better for Thick Discs because of the method for checking visibility.
> Attempt to fix thick disc transfer functions

- src/corona/emissivity.jl
- src/corona/models/extended.jl
- src/corona/models/lamp-post.jl
- src/corona/models/ring.jl
How it escaped my attention in the past is beyond me, but apparently we had only been computing stationary extended coronae. When the corona is co-rotating, loads of problems entered because the assumptions I'd made turned out no longer to be true. 
This PR finalises some work I'd been doing in the last few weeks on rectifying that problem, and implements a brand new technique for interpolating emissivity functions quickly.
For consistently high resolution results (1 to 1000 rg with 2000 bins) even with edge case parameters, it takes about 1500 * 400 geodesics (~30 seconds of runtime on my laptop) for each ring used in the approximation.
For decent results for most of the parameter space, 1000 * 150 geodesics (~8 ish seconds) are sufficient. 
These numbers are still much higher than I'd …
> Fix: most of the problems with a co-rotating extended corona
